pipeline:
  agent: any
  environment:
    AWS_DEFAULT_REGION: "your-region"
    AWS_ACCESS_KEY_ID: credentials('aws-access-key-id')
    AWS_SECRET_ACCESS_KEY: credentials('aws-secret-access-key')
  stages:
    - stage: 'Build'
      steps:
        - sh: 'terraform init'
        - sh: 'terraform validate'
        - sh: 'terraform plan -out=tfplan'
    - stage: 'Test'
      steps:
        - // Run tests
    - stage: 'Deploy'
      steps:
        - sh: 'terraform apply -auto-approve tfplan'
  post:
    always:
      steps:
        - sh: 'terraform destroy -auto-approve'
        
